// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Address defines model for Address.
type Address struct {
	City       string    `json:"city"`
	CreatedAt  time.Time `json:"createdAt"`
	Id         int64     `json:"id"`
	Line1      string    `json:"line1"`
	MemberId   int64     `json:"memberId"`
	PostalCode string    `json:"postalCode"`
	Prefecture string    `json:"prefecture"`
	Recipient  string    `json:"recipient"`
}

// AddressInput defines model for AddressInput.
type AddressInput struct {
	City       string `binding:"required" json:"city"`
	Line1      string `binding:"required" json:"line1"`
	PostalCode string `binding:"required" json:"postalCode"`
	Prefecture string `binding:"required" json:"prefecture"`
	Recipient  string `binding:"required" json:"recipient"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	DisplayName string              `binding:"required" json:"displayName"`
	Email       openapi_types.Email `binding:"required,email" json:"email"`

	// Password 平文。サーバ側で bcrypt ハッシュ化して保存する。
	Password string `binding:"required,min=8" json:"password"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Email    openapi_types.Email `binding:"required,email" json:"email"`
	Password string              `binding:"required" json:"password"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラー種別 (snake_case)。取りうる値は共通ミドルウェア server/internal/middleware (ErrorJSON / AppError) を唯一の出所とする。
	Code string `json:"code"`

	// Message 人間可読なエラー説明 (内部詳細を含む 500 系は固定文言に伏せる)
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName string    `json:"displayName"`
	Email       string    `json:"email"`
	Id          int64     `json:"id"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Id 不透明トークン。Cookie に載せ、検証/破棄時に {id} として送る。
	Id       string `json:"id"`
	MemberId int64  `json:"memberId"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	DisplayName string              `binding:"required" json:"displayName"`
	Email       openapi_types.Email `binding:"required,email" json:"email"`
}

// AddressIdPath defines model for AddressIdPath.
type AddressIdPath = int64

// IdPath defines model for IdPath.
type IdPath = int64

// SessionIdPath defines model for SessionIdPath.
type SessionIdPath = string

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// CreateAddressJSONRequestBody defines body for CreateAddress for application/json ContentType.
type CreateAddressJSONRequestBody = AddressInput

// UpdateAddressJSONRequestBody defines body for UpdateAddress for application/json ContentType.
type UpdateAddressJSONRequestBody = AddressInput

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// 会員一覧
	// (GET /members)
	ListMembers(c *gin.Context)
	// 会員を作成
	// (POST /members)
	CreateMember(c *gin.Context)
	// 会員を取得
	// (GET /members/{id})
	GetMember(c *gin.Context, id IdPath)
	// 会員を更新
	// (PUT /members/{id})
	UpdateMember(c *gin.Context, id IdPath)
	// 会員の住所帳一覧
	// (GET /members/{id}/addresses)
	ListAddresses(c *gin.Context, id IdPath)
	// 住所を住所帳に追加
	// (POST /members/{id}/addresses)
	CreateAddress(c *gin.Context, id IdPath)
	// 住所を削除
	// (DELETE /members/{id}/addresses/{addressId})
	DeleteAddress(c *gin.Context, id IdPath, addressId AddressIdPath)
	// 住所を取得
	// (GET /members/{id}/addresses/{addressId})
	GetAddress(c *gin.Context, id IdPath, addressId AddressIdPath)
	// 住所を更新
	// (PUT /members/{id}/addresses/{addressId})
	UpdateAddress(c *gin.Context, id IdPath, addressId AddressIdPath)
	// ログイン (セッション作成)
	// (POST /sessions)
	CreateSession(c *gin.Context)
	// ログアウト (セッション破棄)
	// (DELETE /sessions/{id})
	DeleteSession(c *gin.Context, id SessionIdPath)
	// セッション検証 (id から会員を引く)
	// (GET /sessions/{id})
	GetSession(c *gin.Context, id SessionIdPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMembers(c)
}

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMember(c)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMember(c, id)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMember(c, id)
}

// ListAddresses operation middleware
func (siw *ServerInterfaceWrapper) ListAddresses(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAddresses(c, id)
}

// CreateAddress operation middleware
func (siw *ServerInterfaceWrapper) CreateAddress(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAddress(c, id)
}

// DeleteAddress operation middleware
func (siw *ServerInterfaceWrapper) DeleteAddress(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "addressId" -------------
	var addressId AddressIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "addressId", c.Param("addressId"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter addressId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAddress(c, id, addressId)
}

// GetAddress operation middleware
func (siw *ServerInterfaceWrapper) GetAddress(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "addressId" -------------
	var addressId AddressIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "addressId", c.Param("addressId"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter addressId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAddress(c, id, addressId)
}

// UpdateAddress operation middleware
func (siw *ServerInterfaceWrapper) UpdateAddress(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "addressId" -------------
	var addressId AddressIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "addressId", c.Param("addressId"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter addressId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAddress(c, id, addressId)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSession(c)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSession(c, id)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/members", wrapper.ListMembers)
	router.POST(options.BaseURL+"/members", wrapper.CreateMember)
	router.GET(options.BaseURL+"/members/:id", wrapper.GetMember)
	router.PUT(options.BaseURL+"/members/:id", wrapper.UpdateMember)
	router.GET(options.BaseURL+"/members/:id/addresses", wrapper.ListAddresses)
	router.POST(options.BaseURL+"/members/:id/addresses", wrapper.CreateAddress)
	router.DELETE(options.BaseURL+"/members/:id/addresses/:addressId", wrapper.DeleteAddress)
	router.GET(options.BaseURL+"/members/:id/addresses/:addressId", wrapper.GetAddress)
	router.PUT(options.BaseURL+"/members/:id/addresses/:addressId", wrapper.UpdateAddress)
	router.POST(options.BaseURL+"/sessions", wrapper.CreateSession)
	router.DELETE(options.BaseURL+"/sessions/:id", wrapper.DeleteSession)
	router.GET(options.BaseURL+"/sessions/:id", wrapper.GetSession)
}
