// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	DisplayName string              `binding:"required" json:"displayName"`
	Email       openapi_types.Email `binding:"required,email" json:"email"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラー種別。 bad_request (400) / not_found (404) / conflict (409) / unprocessable_entity (422) / internal (500) など。
	Code string `json:"code"`

	// Message 人間可読なエラー説明 (内部詳細を含む 500 系は固定文言に伏せる)
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName string    `json:"displayName"`
	Email       string    `json:"email"`
	Id          int64     `json:"id"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	DisplayName string              `binding:"required" json:"displayName"`
	Email       openapi_types.Email `binding:"required,email" json:"email"`
}

// IdPath defines model for IdPath.
type IdPath = int64

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// 会員一覧
	// (GET /members)
	ListMembers(c *gin.Context)
	// 会員を作成
	// (POST /members)
	CreateMember(c *gin.Context)
	// 会員を取得
	// (GET /members/{id})
	GetMember(c *gin.Context, id IdPath)
	// 会員を更新
	// (PUT /members/{id})
	UpdateMember(c *gin.Context, id IdPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMembers(c)
}

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMember(c)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMember(c, id)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMember(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/members", wrapper.ListMembers)
	router.POST(options.BaseURL+"/members", wrapper.CreateMember)
	router.GET(options.BaseURL+"/members/:id", wrapper.GetMember)
	router.PUT(options.BaseURL+"/members/:id", wrapper.UpdateMember)
}
