// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product.products (sku, name, price_cents)
VALUES ($1, $2, $3)
RETURNING id, sku, name, price_cents, created_at
`

type CreateProductParams struct {
	Sku        string `json:"sku"`
	Name       string `json:"name"`
	PriceCents int64  `json:"priceCents"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Sku, arg.Name, arg.PriceCents)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, sku, name, price_cents, created_at
FROM product.products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, price_cents, created_at
FROM product.products
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
