// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
)

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, price_cents, created_at
FROM product.products
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
