// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ListProducts(ctx context.Context) ([]ProductProduct, error)
}

var _ Querier = (*Queries)(nil)
