-- ADR-[[202606231000]]
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'member_svc') THEN CREATE ROLE member_svc LOGIN PASSWORD 'member_pass'; END IF;
END $$;

GRANT USAGE ON SCHEMA member TO member_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA member TO member_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA member TO member_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA member GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO member_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA member GRANT USAGE, SELECT                  ON SEQUENCES TO member_svc;
