-- ADR-[[202606231000]]
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'order_svc')   THEN CREATE ROLE order_svc   LOGIN PASSWORD 'order_pass';   END IF;
END $$;

GRANT USAGE ON SCHEMA "order" TO order_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA "order" TO order_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA "order" TO order_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA "order" GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO order_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA "order" GRANT USAGE, SELECT                  ON SEQUENCES TO order_svc;
