-- ADR-[[202606231000]]
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'payment_svc') THEN CREATE ROLE payment_svc LOGIN PASSWORD 'payment_pass'; END IF;
END $$;

GRANT USAGE ON SCHEMA payment TO payment_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA payment TO payment_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA payment TO payment_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA payment GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO payment_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA payment GRANT USAGE, SELECT                  ON SEQUENCES TO payment_svc;
