-- ADR-[[202606231000]]
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'product_svc')  THEN CREATE ROLE product_svc  LOGIN PASSWORD 'product_pass';  END IF;
END $$;

GRANT USAGE ON SCHEMA product TO product_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA product TO product_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA product TO product_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA product GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO product_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA product GRANT USAGE, SELECT                  ON SEQUENCES TO product_svc;
