-- ADR-[[202606231000]]
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'shipping_svc') THEN CREATE ROLE shipping_svc LOGIN PASSWORD 'shipping_pass'; END IF;
END $$;

GRANT USAGE ON SCHEMA shipping TO shipping_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA shipping TO shipping_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA shipping TO shipping_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA shipping GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO shipping_svc;
ALTER DEFAULT PRIVILEGES FOR ROLE ec IN SCHEMA shipping GRANT USAGE, SELECT                  ON SEQUENCES TO shipping_svc;
