coverage:
  paths:
    - cover.out
  acceptable: 60%

codeToTestRatio:
  code:
    - "server/**/*.go"
    - "!server/**/*_test.go"
    - "!server/**/api.gen.go"
    - "!server/**/internal/db/**"
    - "!server/**/internal/di/inject_band.go"
    - "!server/**/internal/test/db/**"
  test:
    - "server/**/*_test.go"

summary:
  if: "true"

comment:
  if: "true"
