// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/rin2yh/study-service-base-architecture/services/member/internal/handler"
	"github.com/rin2yh/study-service-base-architecture/services/member/internal/repository"
)

func InitHandler(ctx context.Context) (*handler.Handler, error) {
	var err error
	pool, err := kessoku.Async(kessoku.Provide(repository.NewPool)).Fn()(ctx)
	if err != nil {
		var zero *handler.Handler
		return zero, err
	}
	repository0 := kessoku.Bind[repository.MemberRepository](kessoku.Provide(repository.NewRepository)).Fn()(pool)
	handler0 := kessoku.Provide(handler.New).Fn()(repository0)
	return handler0, nil
}
