/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Payment Service API
 * 決済ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import type { CreatePaymentRequest, ErrorResponse, Payment, UpdatePaymentRequest } from "../model";

import { paymentFetch } from "../../mutator";

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type listPaymentsResponse200 = {
  data: Payment[];
  status: 200;
};

export type listPaymentsResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type listPaymentsResponseSuccess = listPaymentsResponse200 & {
  headers: Headers;
};
export type listPaymentsResponseError = listPaymentsResponseDefault & {
  headers: Headers;
};

export type listPaymentsResponse = listPaymentsResponseSuccess | listPaymentsResponseError;

export const getListPaymentsUrl = () => {
  return `/payments`;
};

/**
 * @summary 決済一覧
 */
export const listPayments = async (options?: RequestInit): Promise<listPaymentsResponse> => {
  return paymentFetch<listPaymentsResponse>(getListPaymentsUrl(), {
    ...options,
    method: "GET",
  });
};

export type createPaymentResponse201 = {
  data: Payment;
  status: 201;
};

export type createPaymentResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 201>;
};

export type createPaymentResponseSuccess = createPaymentResponse201 & {
  headers: Headers;
};
export type createPaymentResponseError = createPaymentResponseDefault & {
  headers: Headers;
};

export type createPaymentResponse = createPaymentResponseSuccess | createPaymentResponseError;

export const getCreatePaymentUrl = () => {
  return `/payments`;
};

/**
 * @summary 決済を作成
 */
export const createPayment = async (
  createPaymentRequest: CreatePaymentRequest,
  options?: RequestInit,
): Promise<createPaymentResponse> => {
  return paymentFetch<createPaymentResponse>(getCreatePaymentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPaymentRequest),
  });
};

export type getPaymentResponse200 = {
  data: Payment;
  status: 200;
};

export type getPaymentResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type getPaymentResponseSuccess = getPaymentResponse200 & {
  headers: Headers;
};
export type getPaymentResponseError = getPaymentResponseDefault & {
  headers: Headers;
};

export type getPaymentResponse = getPaymentResponseSuccess | getPaymentResponseError;

export const getGetPaymentUrl = (id: number) => {
  return `/payments/${id}`;
};

/**
 * @summary 決済を取得
 */
export const getPayment = async (
  id: number,
  options?: RequestInit,
): Promise<getPaymentResponse> => {
  return paymentFetch<getPaymentResponse>(getGetPaymentUrl(id), {
    ...options,
    method: "GET",
  });
};

export type updatePaymentResponse200 = {
  data: Payment;
  status: 200;
};

export type updatePaymentResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type updatePaymentResponseSuccess = updatePaymentResponse200 & {
  headers: Headers;
};
export type updatePaymentResponseError = updatePaymentResponseDefault & {
  headers: Headers;
};

export type updatePaymentResponse = updatePaymentResponseSuccess | updatePaymentResponseError;

export const getUpdatePaymentUrl = (id: number) => {
  return `/payments/${id}`;
};

/**
 * @summary 決済を更新
 */
export const updatePayment = async (
  id: number,
  updatePaymentRequest: UpdatePaymentRequest,
  options?: RequestInit,
): Promise<updatePaymentResponse> => {
  return paymentFetch<updatePaymentResponse>(getUpdatePaymentUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updatePaymentRequest),
  });
};
