/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Payment Service API
 * 決済ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorResponse, Payment } from "../model";

import { paymentFetch } from "../../mutator";

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type listPaymentsResponse200 = {
  data: Payment[];
  status: 200;
};

export type listPaymentsResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type listPaymentsResponseSuccess = listPaymentsResponse200 & {
  headers: Headers;
};
export type listPaymentsResponseError = listPaymentsResponseDefault & {
  headers: Headers;
};

export type listPaymentsResponse = listPaymentsResponseSuccess | listPaymentsResponseError;

export const getListPaymentsUrl = () => {
  return `/payments`;
};

/**
 * @summary 決済一覧
 */
export const listPayments = async (options?: RequestInit): Promise<listPaymentsResponse> => {
  return paymentFetch<listPaymentsResponse>(getListPaymentsUrl(), {
    ...options,
    method: "GET",
  });
};
