/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Payment Service API
 * 決済ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary 決済一覧
 */
export const ListPaymentsResponseItem = zod.object({
  id: zod.number(),
  orderId: zod.number(),
  amountCents: zod.number(),
  method: zod.string(),
  status: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});
export const ListPaymentsResponse = zod.array(ListPaymentsResponseItem);
