/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Member Service API
 * 会員ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary 会員一覧
 */
export const ListMembersResponseItem = zod.object({
  id: zod.number(),
  email: zod.string(),
  displayName: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});
export const ListMembersResponse = zod.array(ListMembersResponseItem);

/**
 * @summary 会員を作成
 */
export const CreateMemberBody = zod.object({
  email: zod.email(),
  displayName: zod.string(),
});

export const CreateMemberResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  displayName: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary 会員を取得
 */
export const GetMemberParams = zod.object({
  id: zod.number().describe("リソース ID"),
});

export const GetMemberResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  displayName: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary 会員を更新
 */
export const UpdateMemberParams = zod.object({
  id: zod.number().describe("リソース ID"),
});

export const UpdateMemberBody = zod.object({
  email: zod.email(),
  displayName: zod.string(),
});

export const UpdateMemberResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  displayName: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});
