#!/usr/bin/env bash
# why: 定期実行のたびに PR が増えると誰も見なくなる。固定ブランチへ force push し、open な PR が
#      あれば作り直さず更新に寄せる。人の判断を挟むため必ず draft で出す。
set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root" || exit 1

title="${1:?title required}"
body="${2:?body required}"
branch="${BRANCH:?BRANCH required}"

if git diff --quiet; then
  echo "差分なし: PR は作りません"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

git checkout -B "$branch"
git add -A
git commit -q -m "docs: $title"
git push -f -u origin "$branch"

if [ -n "$(gh pr list --head "$branch" --state open --json number --jq '.[].number')" ]; then
  echo "既存の open PR を更新しました: $branch"
  exit 0
fi

gh pr create --draft --base main --head "$branch" --title "docs: $title" --body "$body

自動生成された PR です。マージ前に実装との突合をレビューしてください。

---
_Generated by [Claude Code](https://claude.ai/code)_"
