#!/usr/bin/env bash
# why: 定期実行のたびに PR が増えると誰も見なくなる。固定ブランチへ force push し、open な PR が
#      あれば作り直さず更新に寄せる。人の判断を挟むため必ず draft で出す。
set -euo pipefail

cd "$(dirname "$0")/../.." || exit 1

branch="${1:?usage: open-pr.sh <branch> <title> <body>}"
title="${2:?usage: open-pr.sh <branch> <title> <body>}"
body="${3:?usage: open-pr.sh <branch> <title> <body>}"

# 後段が git add -A で拾う範囲と判定をそろえる (stage 済み・未追跡も差分として数える)。
if [ -z "$(git status --porcelain)" ]; then
  echo "差分なし: PR は作りません"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# 認証情報を checkout 時点から残さず、push する直前に入れる。docs-agent は同じ job で
# サードパーティの CLI を動かすため、残置した token を盗まれる窓を作らない (.claude/rules/ci.md)。
if [ -n "${GH_TOKEN:-}" ] && [ -n "${GITHUB_REPOSITORY:-}" ]; then
  git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
fi

git checkout -B "$branch"
git add -A
git commit -q -m "docs: $title"
git push -f -u origin "$branch"

if [ -n "$(gh pr list --head "$branch" --state open --json number --jq '.[].number')" ]; then
  echo "既存の open PR を更新しました: $branch"
  exit 0
fi

gh pr create --draft --base main --head "$branch" --title "docs: $title" --body "$body

自動生成された PR です。マージ前に実装との突合をレビューしてください。

---
_Generated by [Claude Code](https://claude.ai/code)_"
