// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/rin2yh/study-architecture/server/order/internal/handler"
	"github.com/rin2yh/study-architecture/server/order/internal/repository"
)

func InitHandler(ctx context.Context) (*handler.Handler, error) {
	var err error
	pool, err := kessoku.Async(kessoku.Provide(repository.NewPool)).Fn()(ctx)
	if err != nil {
		var zero *handler.Handler
		return zero, err
	}
	orderQuery := kessoku.Bind[handler.Query](kessoku.Provide(repository.NewOrderQuery)).Fn()(pool)
	orderCommand := kessoku.Bind[handler.Command](kessoku.Provide(repository.NewOrderCommand)).Fn()(pool)
	handler0 := kessoku.Provide(handler.New).Fn()(orderQuery, orderCommand)
	return handler0, nil
}
