// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	AmountCents int64  `json:"amountCents"`
	Method      string `binding:"required" json:"method"`
	OrderId     int64  `binding:"required,gt=0" json:"orderId"`
	Status      string `binding:"required" json:"status"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラー種別 (snake_case)。取りうる値は共通ミドルウェア server/internal/middleware (ErrorJSON / AppError) を唯一の出所とする。
	Code string `json:"code"`

	// Message 人間可読なエラー説明 (内部詳細を含む 500 系は固定文言に伏せる)
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Payment defines model for Payment.
type Payment struct {
	AmountCents int64     `json:"amountCents"`
	CreatedAt   time.Time `json:"createdAt"`
	Id          int64     `json:"id"`
	Method      string    `json:"method"`
	OrderId     int64     `json:"orderId"`
	Status      string    `json:"status"`
}

// UpdatePaymentRequest defines model for UpdatePaymentRequest.
type UpdatePaymentRequest struct {
	Status string `binding:"required" json:"status"`
}

// IdPath defines model for IdPath.
type IdPath = int64

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = CreatePaymentRequest

// UpdatePaymentJSONRequestBody defines body for UpdatePayment for application/json ContentType.
type UpdatePaymentJSONRequestBody = UpdatePaymentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// 決済一覧
	// (GET /payments)
	ListPayments(c *gin.Context)
	// 決済を作成
	// (POST /payments)
	CreatePayment(c *gin.Context)
	// 決済を取得
	// (GET /payments/{id})
	GetPayment(c *gin.Context, id IdPath)
	// 決済を更新
	// (PUT /payments/{id})
	UpdatePayment(c *gin.Context, id IdPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// ListPayments operation middleware
func (siw *ServerInterfaceWrapper) ListPayments(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPayments(c)
}

// CreatePayment operation middleware
func (siw *ServerInterfaceWrapper) CreatePayment(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePayment(c)
}

// GetPayment operation middleware
func (siw *ServerInterfaceWrapper) GetPayment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPayment(c, id)
}

// UpdatePayment operation middleware
func (siw *ServerInterfaceWrapper) UpdatePayment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePayment(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/payments", wrapper.ListPayments)
	router.POST(options.BaseURL+"/payments", wrapper.CreatePayment)
	router.GET(options.BaseURL+"/payments/:id", wrapper.GetPayment)
	router.PUT(options.BaseURL+"/payments/:id", wrapper.UpdatePayment)
}
