// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Availability defines model for Availability.
type Availability struct {
	Available int64 `json:"available"`
	ProductId int64 `json:"productId"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラー種別 (snake_case)
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// ReservationResult defines model for ReservationResult.
type ReservationResult struct {
	OrderId int64 `json:"orderId"`
}

// ReserveLine defines model for ReserveLine.
type ReserveLine struct {
	ProductId int64 `binding:"required,gt=0" json:"productId"`
	Quantity  int   `binding:"required,gt=0" json:"quantity"`
}

// ReserveRequest defines model for ReserveRequest.
type ReserveRequest struct {
	Lines   []ReserveLine `binding:"required,min=1,dive" json:"lines"`
	OrderId int64         `binding:"required,gt=0" json:"orderId"`
}

// StockIn defines model for StockIn.
type StockIn struct {
	Id        int64 `json:"id"`
	ProductId int64 `json:"productId"`
	Quantity  int   `json:"quantity"`
}

// StockInRequest defines model for StockInRequest.
type StockInRequest struct {
	ProductId int64 `binding:"required,gt=0" json:"productId"`
	Quantity  int   `binding:"required,gt=0" json:"quantity"`
}

// OrderIdPath defines model for OrderIdPath.
type OrderIdPath = int64

// ProductIdPath defines model for ProductIdPath.
type ProductIdPath = int64

// ReserveJSONRequestBody defines body for Reserve for application/json ContentType.
type ReserveJSONRequestBody = ReserveRequest

// StockInJSONRequestBody defines body for StockIn for application/json ContentType.
type StockInJSONRequestBody = StockInRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 商品の利用可能在庫を取得する
	// (GET /availability/{productId})
	GetAvailability(c *gin.Context, productId ProductIdPath)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// 注文の在庫を予約する (在庫不足は 409)
	// (POST /reservations)
	Reserve(c *gin.Context)
	// 注文の未確定予約を解放する (補償・キャンセル)
	// (POST /reservations/{orderId}/release)
	ReleaseReservation(c *gin.Context, orderId OrderIdPath)
	// 入庫を追記する
	// (POST /stock-ins)
	StockIn(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAvailability operation middleware
func (siw *ServerInterfaceWrapper) GetAvailability(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAvailability(c, productId)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// Reserve operation middleware
func (siw *ServerInterfaceWrapper) Reserve(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Reserve(c)
}

// ReleaseReservation operation middleware
func (siw *ServerInterfaceWrapper) ReleaseReservation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", c.Param("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReleaseReservation(c, orderId)
}

// StockIn operation middleware
func (siw *ServerInterfaceWrapper) StockIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StockIn(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/availability/:productId", wrapper.GetAvailability)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.POST(options.BaseURL+"/reservations", wrapper.Reserve)
	router.POST(options.BaseURL+"/reservations/:orderId/release", wrapper.ReleaseReservation)
	router.POST(options.BaseURL+"/stock-ins", wrapper.StockIn)
}
