// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"
)

const availableQty = `-- name: AvailableQty :one
SELECT COALESCE(SUM(d.delta), 0)::bigint AS available
FROM (
    SELECT s.quantity::bigint AS delta
    FROM inventory.stock_ins s
    WHERE s.product_id = $1
  UNION ALL
    SELECT -r.quantity::bigint
    FROM inventory.reservations r
    WHERE r.product_id = $1 AND r.confirmed_at IS NOT NULL
  UNION ALL
    SELECT -r.quantity::bigint
    FROM inventory.reservations r
    WHERE r.product_id = $1
      AND r.confirmed_at IS NULL AND r.released_at IS NULL AND r.expired_at IS NULL
      AND r.created_at + inventory.reservation_ttl() > now()
) d
`

// 在庫数を保存せず集計で導く (ADR-[[202606262000]])。
func (q *Queries) AvailableQty(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRow(ctx, availableQty, productID)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const confirmReservationsByOrder = `-- name: ConfirmReservationsByOrder :exec
UPDATE inventory.reservations
SET confirmed_at = now()
WHERE order_id = $1 AND confirmed_at IS NULL AND released_at IS NULL AND expired_at IS NULL
`

// 終端 *_at が未設定の予約だけ確定する。payment.settled 再配信は 0 行更新で吸収 (ADR-[[202606261214]])。
func (q *Queries) ConfirmReservationsByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, confirmReservationsByOrder, orderID)
	return err
}

const expireReservations = `-- name: ExpireReservations :exec
UPDATE inventory.reservations
SET expired_at = now()
WHERE confirmed_at IS NULL AND released_at IS NULL AND expired_at IS NULL
  AND created_at + inventory.reservation_ttl() <= now()
`

// (ADR-[[202606262000]])
func (q *Queries) ExpireReservations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireReservations)
	return err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO inventory.reservations (product_id, order_id, quantity)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertReservationParams struct {
	ProductID int64 `json:"productId"`
	OrderID   int64 `json:"orderId"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReservation, arg.ProductID, arg.OrderID, arg.Quantity)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockProduct = `-- name: LockProduct :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// 同一商品の同時予約を直列化する。tx 終了まで保持され売り越しを DB で防ぐ (ADR-[[202606262000]])。
func (q *Queries) LockProduct(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, lockProduct, dollar_1)
	return err
}

const releaseReservationsByOrder = `-- name: ReleaseReservationsByOrder :exec
UPDATE inventory.reservations
SET released_at = now()
WHERE order_id = $1 AND confirmed_at IS NULL AND released_at IS NULL AND expired_at IS NULL
`

// 補償/キャンセル時の解放 (#88 のフック)。
func (q *Queries) ReleaseReservationsByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, releaseReservationsByOrder, orderID)
	return err
}

const restockConfirmedReservationsByOrder = `-- name: RestockConfirmedReservationsByOrder :exec
INSERT INTO inventory.stock_ins (product_id, quantity, reservation_id)
SELECT r.product_id, r.quantity, r.id
FROM inventory.reservations r
WHERE r.order_id = $1 AND r.confirmed_at IS NOT NULL
ON CONFLICT (reservation_id) WHERE reservation_id IS NOT NULL DO NOTHING
`

// (ADR-[[202606281000]])
func (q *Queries) RestockConfirmedReservationsByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, restockConfirmedReservationsByOrder, orderID)
	return err
}

const stockIn = `-- name: StockIn :one
INSERT INTO inventory.stock_ins (product_id, quantity)
VALUES ($1, $2)
RETURNING id, product_id, quantity, created_at, reservation_id
`

type StockInParams struct {
	ProductID int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) StockIn(ctx context.Context, arg StockInParams) (InventoryStockIn, error) {
	row := q.db.QueryRow(ctx, stockIn, arg.ProductID, arg.Quantity)
	var i InventoryStockIn
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.ReservationID,
	)
	return i, err
}
