// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const availableQty = `-- name: AvailableQty :one
SELECT (
    COALESCE(SUM(m.quantity) FILTER (WHERE m.kind = 'stock_in'), 0)
  - COALESCE(SUM(m.quantity) FILTER (WHERE m.kind = 'confirm'), 0)
  - COALESCE(SUM(m.quantity) FILTER (
        WHERE m.kind = 'reserve'
          AND m.expires_at > now()
          AND NOT EXISTS (SELECT 1 FROM inventory.movements c WHERE c.kind = 'confirm' AND c.reservation_id = m.id)
          AND NOT EXISTS (SELECT 1 FROM inventory.movements x WHERE x.kind = 'release' AND x.reservation_id = m.id)
    ), 0)
)::bigint AS available
FROM inventory.movements m
WHERE m.product_id = $1
`

func (q *Queries) AvailableQty(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRow(ctx, availableQty, productID)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const confirmReservationsByOrder = `-- name: ConfirmReservationsByOrder :exec
INSERT INTO inventory.movements (product_id, kind, quantity, order_id, reservation_id)
SELECT r.product_id, 'confirm', r.quantity, r.order_id, r.id
FROM inventory.movements r
WHERE r.kind = 'reserve' AND r.order_id = $1
  AND NOT EXISTS (SELECT 1 FROM inventory.movements x WHERE x.kind = 'release' AND x.reservation_id = r.id)
ON CONFLICT (reservation_id) WHERE kind = 'confirm' DO NOTHING
`

// 予約→確定の昇格。payment.settled 再配信は部分ユニークインデックスで吸収する (ADR-[[202606261214]])。
func (q *Queries) ConfirmReservationsByOrder(ctx context.Context, orderID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, confirmReservationsByOrder, orderID)
	return err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO inventory.movements (product_id, kind, quantity, order_id, expires_at)
VALUES ($1, 'reserve', $2, $3, now() + ($4::int * interval '1 second'))
RETURNING id
`

type InsertReservationParams struct {
	ProductID int64       `json:"productId"`
	Quantity  int32       `json:"quantity"`
	OrderID   pgtype.Int8 `json:"orderId"`
	Column4   int32       `json:"column4"`
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.ProductID,
		arg.Quantity,
		arg.OrderID,
		arg.Column4,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockProduct = `-- name: LockProduct :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// 同一商品の同時予約を直列化する。tx 終了まで保持され売り越しを DB で防ぐ (ADR-[[202606262000]])。
func (q *Queries) LockProduct(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, lockProduct, dollar_1)
	return err
}

const releaseExpiredReservations = `-- name: ReleaseExpiredReservations :exec
INSERT INTO inventory.movements (product_id, kind, quantity, order_id, reservation_id)
SELECT r.product_id, 'release', r.quantity, r.order_id, r.id
FROM inventory.movements r
WHERE r.kind = 'reserve' AND r.expires_at <= now()
  AND NOT EXISTS (SELECT 1 FROM inventory.movements c WHERE c.kind = 'confirm' AND c.reservation_id = r.id)
  AND NOT EXISTS (SELECT 1 FROM inventory.movements x WHERE x.kind = 'release' AND x.reservation_id = r.id)
ON CONFLICT (reservation_id) WHERE kind = 'release' DO NOTHING
`

// TTL 切れ予約の遅延回収。worker が定期実行し台帳に解放を追記する (ADR-[[202606262000]])。
func (q *Queries) ReleaseExpiredReservations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, releaseExpiredReservations)
	return err
}

const releaseReservationsByOrder = `-- name: ReleaseReservationsByOrder :exec
INSERT INTO inventory.movements (product_id, kind, quantity, order_id, reservation_id)
SELECT r.product_id, 'release', r.quantity, r.order_id, r.id
FROM inventory.movements r
WHERE r.kind = 'reserve' AND r.order_id = $1
  AND NOT EXISTS (SELECT 1 FROM inventory.movements c WHERE c.kind = 'confirm' AND c.reservation_id = r.id)
ON CONFLICT (reservation_id) WHERE kind = 'release' DO NOTHING
`

// 補償/キャンセル時の解放。未確定の予約だけを反対仕訳で戻す (#88 のフック)。
func (q *Queries) ReleaseReservationsByOrder(ctx context.Context, orderID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, releaseReservationsByOrder, orderID)
	return err
}

const stockIn = `-- name: StockIn :one
INSERT INTO inventory.movements (product_id, kind, quantity)
VALUES ($1, 'stock_in', $2)
RETURNING id, product_id, kind, quantity, order_id, reservation_id, expires_at, created_at
`

type StockInParams struct {
	ProductID int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) StockIn(ctx context.Context, arg StockInParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, stockIn, arg.ProductID, arg.Quantity)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.Quantity,
		&i.OrderID,
		&i.ReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
