// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"
)

const availableQty = `-- name: AvailableQty :one
SELECT COALESCE(SUM(d.delta), 0)::bigint AS available
FROM (
    SELECT s.quantity::bigint AS delta
    FROM inventory.stock_ins s
    WHERE s.product_id = $1
  UNION ALL
    SELECT -r.quantity::bigint
    FROM inventory.reservations r
    JOIN inventory.confirmations c ON c.reservation_id = r.id
    WHERE r.product_id = $1
  UNION ALL
    SELECT -r.quantity::bigint
    FROM inventory.reservations r
    WHERE r.product_id = $1 AND r.expires_at > now()
      AND NOT EXISTS (SELECT 1 FROM inventory.confirmations c WHERE c.reservation_id = r.id)
      AND NOT EXISTS (SELECT 1 FROM inventory.releases x WHERE x.reservation_id = r.id)
) d
`

// 利用可能在庫 = 入庫(+) と、確定・未確定で生きている予約(-) の符号付き合計。
func (q *Queries) AvailableQty(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRow(ctx, availableQty, productID)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const confirmReservationsByOrder = `-- name: ConfirmReservationsByOrder :exec
INSERT INTO inventory.confirmations (reservation_id)
SELECT r.id FROM inventory.reservations r
WHERE r.order_id = $1
  AND NOT EXISTS (SELECT 1 FROM inventory.releases x WHERE x.reservation_id = r.id)
  AND NOT EXISTS (SELECT 1 FROM inventory.expirations e WHERE e.reservation_id = r.id)
ON CONFLICT (reservation_id) DO NOTHING
`

// payment.settled 再配信は主キー衝突で吸収する (ADR-[[202606261214]])。終端済み (解放/期限切れ) は確定しない。
func (q *Queries) ConfirmReservationsByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, confirmReservationsByOrder, orderID)
	return err
}

const expireReservations = `-- name: ExpireReservations :exec
INSERT INTO inventory.expirations (reservation_id)
SELECT r.id FROM inventory.reservations r
WHERE r.expires_at <= now()
  AND NOT EXISTS (SELECT 1 FROM inventory.confirmations c WHERE c.reservation_id = r.id)
  AND NOT EXISTS (SELECT 1 FROM inventory.releases x WHERE x.reservation_id = r.id)
ON CONFLICT (reservation_id) DO NOTHING
`

// TTL 期限切れの回収。意図的な解放 (releases) と区別して expirations に記録する (ADR-[[202606262000]])。
func (q *Queries) ExpireReservations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireReservations)
	return err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO inventory.reservations (product_id, order_id, quantity, expires_at)
VALUES ($1, $2, $3, now() + ($4::int * interval '1 second'))
RETURNING id
`

type InsertReservationParams struct {
	ProductID int64 `json:"productId"`
	OrderID   int64 `json:"orderId"`
	Quantity  int32 `json:"quantity"`
	Column4   int32 `json:"column4"`
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.ProductID,
		arg.OrderID,
		arg.Quantity,
		arg.Column4,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockProduct = `-- name: LockProduct :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// 同一商品の同時予約を直列化する。tx 終了まで保持され売り越しを DB で防ぐ (ADR-[[202606262000]])。
func (q *Queries) LockProduct(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, lockProduct, dollar_1)
	return err
}

const releaseReservationsByOrder = `-- name: ReleaseReservationsByOrder :exec
INSERT INTO inventory.releases (reservation_id)
SELECT r.id FROM inventory.reservations r
WHERE r.order_id = $1
  AND NOT EXISTS (SELECT 1 FROM inventory.confirmations c WHERE c.reservation_id = r.id)
  AND NOT EXISTS (SELECT 1 FROM inventory.expirations e WHERE e.reservation_id = r.id)
ON CONFLICT (reservation_id) DO NOTHING
`

// 補償/キャンセル時の解放 (#88 のフック)。終端済み (確定/期限切れ) は解放しない。
func (q *Queries) ReleaseReservationsByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, releaseReservationsByOrder, orderID)
	return err
}

const stockIn = `-- name: StockIn :one
INSERT INTO inventory.stock_ins (product_id, quantity)
VALUES ($1, $2)
RETURNING id, product_id, quantity, created_at
`

type StockInParams struct {
	ProductID int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) StockIn(ctx context.Context, arg StockInParams) (InventoryStockIn, error) {
	row := q.db.QueryRow(ctx, stockIn, arg.ProductID, arg.Quantity)
	var i InventoryStockIn
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
