// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryStockIn struct {
	ID            int64              `json:"id"`
	ProductID     int64              `json:"productId"`
	Quantity      int32              `json:"quantity"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	ReservationID pgtype.Int8        `json:"reservationId"`
}
