// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryMovement struct {
	ID            int64              `json:"id"`
	ProductID     int64              `json:"productId"`
	Kind          string             `json:"kind"`
	Quantity      int32              `json:"quantity"`
	OrderID       pgtype.Int8        `json:"orderId"`
	ReservationID pgtype.Int8        `json:"reservationId"`
	ExpiresAt     pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}
