// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AvailableQty(ctx context.Context, productID int64) (int64, error)
	// 予約→確定の昇格。payment.settled 再配信は部分ユニークインデックスで吸収する (ADR-[[202606261214]])。
	ConfirmReservationsByOrder(ctx context.Context, orderID pgtype.Int8) error
	InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error)
	// 同一商品の同時予約を直列化する。tx 終了まで保持され売り越しを DB で防ぐ (ADR-[[202606262000]])。
	LockProduct(ctx context.Context, dollar_1 int64) error
	// TTL 切れ予約の遅延回収。worker が定期実行し台帳に解放を追記する (ADR-[[202606262000]])。
	ReleaseExpiredReservations(ctx context.Context) error
	// 補償/キャンセル時の解放。未確定の予約だけを反対仕訳で戻す (#88 のフック)。
	ReleaseReservationsByOrder(ctx context.Context, orderID pgtype.Int8) error
	StockIn(ctx context.Context, arg StockInParams) (InventoryMovement, error)
}

var _ Querier = (*Queries)(nil)
