// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/rin2yh/study-architecture/server/internal/redisx"
	"github.com/rin2yh/study-architecture/server/inventory/internal/consumer"
	"github.com/rin2yh/study-architecture/server/inventory/internal/handler"
	"github.com/rin2yh/study-architecture/server/inventory/internal/rdb"
	"github.com/rin2yh/study-architecture/server/inventory/internal/reaper"
	"github.com/rin2yh/study-architecture/server/inventory/internal/worker"
)

func InitHandler(ctx context.Context) (*handler.Handler, error) {
	var err error
	pool, err := kessoku.Async(kessoku.Provide(rdb.NewPool)).Fn()(ctx)
	if err != nil {
		var zero *handler.Handler
		return zero, err
	}
	inventoryQuery := kessoku.Bind[handler.Query](kessoku.Provide(rdb.NewInventoryQuery)).Fn()(pool)
	inventoryCommand := kessoku.Bind[handler.Command](kessoku.Provide(rdb.NewInventoryCommand)).Fn()(pool)
	handler0 := kessoku.Provide(handler.New).Fn()(inventoryQuery, inventoryCommand)
	return handler0, nil
}
func InitWorker(ctx0 context.Context) (*worker.Worker, error) {
	var err0 error
	client, err0 := kessoku.Provide(redisx.NewClient).Fn()()
	if err0 != nil {
		var zero *worker.Worker
		return zero, err0
	}
	var err1 error
	pool0, err1 := kessoku.Async(kessoku.Provide(rdb.NewPool)).Fn()(ctx0)
	if err1 != nil {
		var zero *worker.Worker
		return zero, err1
	}
	inventoryCommand0 := kessoku.Provide(rdb.NewInventoryCommand).Fn()(pool0)
	reservationConfirmer := kessoku.Provide(func(c *rdb.InventoryCommand) consumer.ReservationConfirmer {
		return c
	}).Fn()(inventoryCommand0)
	expiredReleaser := kessoku.Provide(func(c *rdb.InventoryCommand) reaper.ExpiredReleaser {
		return c
	}).Fn()(inventoryCommand0)
	consumer0 := kessoku.Provide(consumer.New).Fn()(client, reservationConfirmer)
	reaper0 := kessoku.Provide(reaper.New).Fn()(expiredReleaser)
	worker0 := kessoku.Provide(worker.New).Fn()(consumer0, reaper0)
	return worker0, nil
}
