// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/rin2yh/study-architecture/server/product/internal/handler"
	"github.com/rin2yh/study-architecture/server/product/internal/repository"
)

func InitHandler(ctx context.Context) (*handler.Handler, error) {
	var err error
	pool, err := kessoku.Async(kessoku.Provide(repository.NewPool)).Fn()(ctx)
	if err != nil {
		var zero *handler.Handler
		return zero, err
	}
	productQuery := kessoku.Bind[handler.Query](kessoku.Provide(repository.NewProductQuery)).Fn()(pool)
	productCommand := kessoku.Bind[handler.Command](kessoku.Provide(repository.NewProductCommand)).Fn()(pool)
	handler0 := kessoku.Provide(handler.New).Fn()(productQuery, productCommand)
	return handler0, nil
}
