// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductProduct struct {
	ID         int64              `json:"id"`
	Sku        string             `json:"sku"`
	Name       string             `json:"name"`
	PriceCents int64              `json:"priceCents"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}
