// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderOrder struct {
	ID         int64              `json:"id"`
	MemberID   int64              `json:"memberId"`
	Status     string             `json:"status"`
	TotalCents int64              `json:"totalCents"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}
