// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderOrder struct {
	ID                        int64              `json:"id"`
	MemberID                  int64              `json:"memberId"`
	Status                    string             `json:"status"`
	TotalCents                int64              `json:"totalCents"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	CancelledEventPending     bool               `json:"cancelledEventPending"`
	CancelledEventTraceparent string             `json:"cancelledEventTraceparent"`
	CancelledEventPublishedAt pgtype.Timestamptz `json:"cancelledEventPublishedAt"`
}

type OrderOrderItem struct {
	ID             int64              `json:"id"`
	OrderID        int64              `json:"orderId"`
	ProductID      int64              `json:"productId"`
	ProductName    string             `json:"productName"`
	UnitPriceCents int64              `json:"unitPriceCents"`
	Quantity       int32              `json:"quantity"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}
