// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order".orders (member_id, status, total_cents)
VALUES ($1, $2, $3)
RETURNING id, member_id, status, total_cents, created_at
`

type CreateOrderParams struct {
	MemberID   int64  `json:"memberId"`
	Status     string `json:"status"`
	TotalCents int64  `json:"totalCents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (OrderOrder, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.MemberID, arg.Status, arg.TotalCents)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO "order".order_items (order_id, product_id, product_name, unit_price_cents, quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, product_name, unit_price_cents, quantity, created_at
`

type CreateOrderItemParams struct {
	OrderID        int64  `json:"orderId"`
	ProductID      int64  `json:"productId"`
	ProductName    string `json:"productName"`
	UnitPriceCents int64  `json:"unitPriceCents"`
	Quantity       int32  `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderOrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.UnitPriceCents,
		arg.Quantity,
	)
	var i OrderOrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.UnitPriceCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "order".orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, member_id, status, total_cents, created_at
FROM "order".orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (OrderOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, product_name, unit_price_cents, quantity, created_at
FROM "order".order_items
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]OrderOrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrderItem{}
	for rows.Next() {
		var i OrderOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.UnitPriceCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, member_id, status, total_cents, created_at
FROM "order".orders
ORDER BY id
`

func (q *Queries) ListOrders(ctx context.Context) ([]OrderOrder, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrder{}
	for rows.Next() {
		var i OrderOrder
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Status,
			&i.TotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByMember = `-- name: ListOrdersByMember :many
SELECT id, member_id, status, total_cents, created_at
FROM "order".orders
WHERE member_id = $1
ORDER BY id
`

func (q *Queries) ListOrdersByMember(ctx context.Context, memberID int64) ([]OrderOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrder{}
	for rows.Next() {
		var i OrderOrder
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Status,
			&i.TotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE "order".orders
SET status = $2
WHERE id = $1
RETURNING id, member_id, status, total_cents, created_at
`

type UpdateOrderParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (OrderOrder, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.ID, arg.Status)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}
