// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"
)

const listOrders = `-- name: ListOrders :many
SELECT id, member_id, status, total_cents, created_at
FROM "order".orders
ORDER BY id
`

func (q *Queries) ListOrders(ctx context.Context) ([]OrderOrder, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrder{}
	for rows.Next() {
		var i OrderOrder
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Status,
			&i.TotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
