// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// 遷移と未送信イベントを同一 tx で確定し、送出はリレーに後追いさせる (ADR-[[202606300600]])。
	CancelOrder(ctx context.Context, id int64) (OrderOrder, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (OrderOrder, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderOrderItem, error)
	CreateOrderWithShipping(ctx context.Context, arg CreateOrderWithShippingParams) (OrderOrder, error)
	DeleteOrder(ctx context.Context, id int64) error
	GetOrder(ctx context.Context, id int64) (OrderOrder, error)
	// 判定〜更新を 1 tx で直列化する (ADR-[[202606261702]])。
	GetOrderForUpdate(ctx context.Context, id int64) (OrderOrder, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	ListOrderItems(ctx context.Context, orderID int64) ([]OrderOrderItem, error)
	ListOrders(ctx context.Context) ([]OrderOrder, error)
	ListOrdersByMember(ctx context.Context, memberID int64) ([]OrderOrder, error)
	ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error)
	MarkOutboxPublished(ctx context.Context, id int64) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (OrderOrder, error)
}

var _ Querier = (*Queries)(nil)
