// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (OrderOrder, error)
	GetOrder(ctx context.Context, id int64) (OrderOrder, error)
	ListOrders(ctx context.Context) ([]OrderOrder, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (OrderOrder, error)
}

var _ Querier = (*Queries)(nil)
