// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: address.sql

package db

import (
	"context"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO member.addresses (member_id, recipient, postal_code, prefecture, city, line1)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, member_id, recipient, postal_code, prefecture, city, line1, created_at
`

type CreateAddressParams struct {
	MemberID   int64  `json:"memberId"`
	Recipient  string `json:"recipient"`
	PostalCode string `json:"postalCode"`
	Prefecture string `json:"prefecture"`
	City       string `json:"city"`
	Line1      string `json:"line1"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.MemberID,
		arg.Recipient,
		arg.PostalCode,
		arg.Prefecture,
		arg.City,
		arg.Line1,
	)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Recipient,
		&i.PostalCode,
		&i.Prefecture,
		&i.City,
		&i.Line1,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM member.addresses
WHERE id = $1 AND member_id = $2
`

type DeleteAddressParams struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"memberId"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.MemberID)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT id, member_id, recipient, postal_code, prefecture, city, line1, created_at
FROM member.addresses
WHERE id = $1 AND member_id = $2
`

type GetAddressParams struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"memberId"`
}

func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, getAddress, arg.ID, arg.MemberID)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Recipient,
		&i.PostalCode,
		&i.Prefecture,
		&i.City,
		&i.Line1,
		&i.CreatedAt,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, member_id, recipient, postal_code, prefecture, city, line1, created_at
FROM member.addresses
WHERE member_id = $1
ORDER BY id
`

func (q *Queries) ListAddresses(ctx context.Context, memberID int64) ([]MemberAddress, error) {
	rows, err := q.db.Query(ctx, listAddresses, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberAddress{}
	for rows.Next() {
		var i MemberAddress
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Recipient,
			&i.PostalCode,
			&i.Prefecture,
			&i.City,
			&i.Line1,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE member.addresses
SET recipient = $3, postal_code = $4, prefecture = $5, city = $6, line1 = $7
WHERE id = $1 AND member_id = $2
RETURNING id, member_id, recipient, postal_code, prefecture, city, line1, created_at
`

type UpdateAddressParams struct {
	ID         int64  `json:"id"`
	MemberID   int64  `json:"memberId"`
	Recipient  string `json:"recipient"`
	PostalCode string `json:"postalCode"`
	Prefecture string `json:"prefecture"`
	City       string `json:"city"`
	Line1      string `json:"line1"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.MemberID,
		arg.Recipient,
		arg.PostalCode,
		arg.Prefecture,
		arg.City,
		arg.Line1,
	)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Recipient,
		&i.PostalCode,
		&i.Prefecture,
		&i.City,
		&i.Line1,
		&i.CreatedAt,
	)
	return i, err
}
