// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member.members (email, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, created_at, password_hash
`

type CreateMemberParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"displayName"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (MemberMember, error) {
	row := q.db.QueryRow(ctx, createMember, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i MemberMember
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, email, display_name, created_at, password_hash
FROM member.members
WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id int64) (MemberMember, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i MemberMember
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, email, display_name, created_at, password_hash
FROM member.members
WHERE email = $1
`

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (MemberMember, error) {
	row := q.db.QueryRow(ctx, getMemberByEmail, email)
	var i MemberMember
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, email, display_name, created_at, password_hash
FROM member.members
ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context) ([]MemberMember, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberMember{}
	for rows.Next() {
		var i MemberMember
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE member.members
SET email = $2, display_name = $3
WHERE id = $1
RETURNING id, email, display_name, created_at, password_hash
`

type UpdateMemberParams struct {
	ID          int64  `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (MemberMember, error) {
	row := q.db.QueryRow(ctx, updateMember, arg.ID, arg.Email, arg.DisplayName)
	var i MemberMember
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}
