// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"
)

const listMembers = `-- name: ListMembers :many
SELECT id, email, display_name, created_at
FROM member.members
ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context) ([]MemberMember, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberMember{}
	for rows.Next() {
		var i MemberMember
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
