// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberAddress struct {
	ID         int64              `json:"id"`
	MemberID   int64              `json:"memberId"`
	Recipient  string             `json:"recipient"`
	PostalCode string             `json:"postalCode"`
	Prefecture string             `json:"prefecture"`
	City       string             `json:"city"`
	Line1      string             `json:"line1"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type MemberMember struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"displayName"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	PasswordHash string             `json:"passwordHash"`
}

type MemberSession struct {
	ID        string             `json:"id"`
	MemberID  int64              `json:"memberId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
