// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberMember struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"displayName"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}
