// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateMember(ctx context.Context, arg CreateMemberParams) (MemberMember, error)
	GetMember(ctx context.Context, id int64) (MemberMember, error)
	ListMembers(ctx context.Context) ([]MemberMember, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (MemberMember, error)
}

var _ Querier = (*Queries)(nil)
