// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO member.sessions (id, member_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, member_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	MemberID  int64              `json:"memberId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (MemberSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.MemberID, arg.ExpiresAt)
	var i MemberSession
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM member.sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, member_id, expires_at, created_at
FROM member.sessions
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id string) (MemberSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i MemberSession
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
