// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CheckoutItem defines model for CheckoutItem.
type CheckoutItem struct {
	ProductId int64 `binding:"required,gt=0" json:"productId"`
	Quantity  int   `binding:"required,gt=0" json:"quantity"`
}

// CheckoutRequest defines model for CheckoutRequest.
type CheckoutRequest struct {
	Items         []CheckoutItem `binding:"required,min=1,dive" json:"items"`
	MemberId      int64          `binding:"required,gt=0" json:"memberId"`
	PaymentMethod string         `binding:"required" json:"paymentMethod"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	MemberId   int64  `binding:"required,gt=0" json:"memberId"`
	Status     string `binding:"required" json:"status"`
	TotalCents int64  `json:"totalCents"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラー種別 (snake_case)。取りうる値は共通ミドルウェア server/internal/middleware (ErrorJSON / AppError) を唯一の出所とする。
	Code string `json:"code"`

	// Message 人間可読なエラー説明 (内部詳細を含む 500 系は固定文言に伏せる)
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Order defines model for Order.
type Order struct {
	CreatedAt  time.Time    `json:"createdAt"`
	Id         int64        `json:"id"`
	Items      *[]OrderItem `json:"items,omitempty"`
	MemberId   int64        `json:"memberId"`
	Status     string       `json:"status"`
	TotalCents int64        `json:"totalCents"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	ProductId      int64  `json:"productId"`
	ProductName    string `json:"productName"`
	Quantity       int    `json:"quantity"`
	UnitPriceCents int64  `json:"unitPriceCents"`
}

// UpdateOrderRequest defines model for UpdateOrderRequest.
type UpdateOrderRequest struct {
	Status string `binding:"required" json:"status"`
}

// IdPath defines model for IdPath.
type IdPath = int64

// MemberIdHeader defines model for MemberIdHeader.
type MemberIdHeader = int64

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// XMemberId 認証済み会員 id。UI のサーバ側ローダがセッション検証後に付与する。 与えられた場合はその会員の注文だけに絞り込む (ADR 0009)。
	XMemberId *MemberIdHeader `json:"X-Member-Id,omitempty"`
}

// CheckoutJSONRequestBody defines body for Checkout for application/json ContentType.
type CheckoutJSONRequestBody = CheckoutRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody = UpdateOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// カートを確定して注文を作成し決済を手配 (明細に商品をスナップショット)
	// (POST /checkout)
	Checkout(c *gin.Context)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// 注文一覧
	// (GET /orders)
	ListOrders(c *gin.Context, params ListOrdersParams)
	// 注文を作成
	// (POST /orders)
	CreateOrder(c *gin.Context)
	// 注文を取得
	// (GET /orders/{id})
	GetOrder(c *gin.Context, id IdPath)
	// 注文を更新
	// (PUT /orders/{id})
	UpdateOrder(c *gin.Context, id IdPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Checkout operation middleware
func (siw *ServerInterfaceWrapper) Checkout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Checkout(c)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Member-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Member-Id")]; found {
		var XMemberId MemberIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Member-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Member-Id", valueList[0], &XMemberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: "int64"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Member-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XMemberId = &XMemberId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListOrders(c, params)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrder(c)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrder(c, id)
}

// UpdateOrder operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrder(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrder(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/checkout", wrapper.Checkout)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/orders", wrapper.ListOrders)
	router.POST(options.BaseURL+"/orders", wrapper.CreateOrder)
	router.GET(options.BaseURL+"/orders/:id", wrapper.GetOrder)
	router.PUT(options.BaseURL+"/orders/:id", wrapper.UpdateOrder)
}
