// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment.payments (order_id, amount_cents, method, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idempotency_key) WHERE idempotency_key <> '' DO NOTHING
RETURNING id, order_id, amount_cents, method, status, created_at, idempotency_key
`

type CreatePaymentParams struct {
	OrderID        int64  `json:"orderId"`
	AmountCents    int64  `json:"amountCents"`
	Method         string `json:"method"`
	Status         string `json:"status"`
	IdempotencyKey string `json:"idempotencyKey"`
}

// ADR-[[202606261214]]
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.AmountCents,
		arg.Method,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, amount_cents, method, status, created_at, idempotency_key FROM payment.payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, order_id, amount_cents, method, status, created_at, idempotency_key FROM payment.payments
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO payment.outbox (aggregate_id, event_type, payload, traceparent)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxParams struct {
	AggregateID int64  `json:"aggregateId"`
	EventType   string `json:"eventType"`
	Payload     []byte `json:"payload"`
	Traceparent string `json:"traceparent"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Traceparent,
	)
	return err
}

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, amount_cents, method, status, created_at, idempotency_key FROM payment.payments
ORDER BY id
`

func (q *Queries) ListPayments(ctx context.Context) ([]PaymentPayment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentPayment{}
	for rows.Next() {
		var i PaymentPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.CreatedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, payload, traceparent
FROM payment.outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

type ListUnpublishedOutboxRow struct {
	ID          int64  `json:"id"`
	Payload     []byte `json:"payload"`
	Traceparent string `json:"traceparent"`
}

func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnpublishedOutboxRow{}
	for rows.Next() {
		var i ListUnpublishedOutboxRow
		if err := rows.Scan(&i.ID, &i.Payload, &i.Traceparent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE payment.outbox
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const refundPaymentByOrder = `-- name: RefundPaymentByOrder :exec
UPDATE payment.payments
SET status = 'refunded'
WHERE order_id = $1 AND status IN ('paid', 'settled', 'captured')
`

// 終端でない確定済み決済だけ返金へ遷移。再配信は 0 行更新で吸収する (ADR-[[202606261214]])。
func (q *Queries) RefundPaymentByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, refundPaymentByOrder, orderID)
	return err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payment.payments
SET status = $2
WHERE id = $1
RETURNING id, order_id, amount_cents, method, status, created_at, idempotency_key
`

type UpdatePaymentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, updatePayment, arg.ID, arg.Status)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const voidPendingPaymentByOrder = `-- name: VoidPendingPaymentByOrder :exec
UPDATE payment.payments
SET status = 'cancelled'
WHERE order_id = $1 AND status = 'pending'
`

// 返金すべき入金がないため refunded とは区別する (ADR-[[202606261702]])。
func (q *Queries) VoidPendingPaymentByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, voidPendingPaymentByOrder, orderID)
	return err
}
