// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment.payments (order_id, amount_cents, method, status)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, amount_cents, method, status, created_at
`

type CreatePaymentParams struct {
	OrderID     int64  `json:"orderId"`
	AmountCents int64  `json:"amountCents"`
	Method      string `json:"method"`
	Status      string `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.AmountCents,
		arg.Method,
		arg.Status,
	)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, amount_cents, method, status, created_at
FROM payment.payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, amount_cents, method, status, created_at
FROM payment.payments
ORDER BY id
`

func (q *Queries) ListPayments(ctx context.Context) ([]PaymentPayment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentPayment{}
	for rows.Next() {
		var i PaymentPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payment.payments
SET status = $2
WHERE id = $1
RETURNING id, order_id, amount_cents, method, status, created_at
`

type UpdatePaymentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, updatePayment, arg.ID, arg.Status)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
