// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// ADR-[[202606261214]]
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (PaymentPayment, error)
	GetPayment(ctx context.Context, id int64) (PaymentPayment, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentPayment, error)
	ListPayments(ctx context.Context) ([]PaymentPayment, error)
	ListUnpublishedSettledEvents(ctx context.Context, limit int32) ([]ListUnpublishedSettledEventsRow, error)
	MarkSettledEventPublished(ctx context.Context, id int64) error
	// 終端でない確定済み決済だけ返金へ遷移。再配信は 0 行更新で吸収する (ADR-[[202606261214]])。
	RefundPaymentByOrder(ctx context.Context, orderID int64) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (PaymentPayment, error)
	// 返金すべき入金がないため refunded とは区別する (ADR-[[202606261702]])。
	VoidPendingPaymentByOrder(ctx context.Context, orderID int64) error
}

var _ Querier = (*Queries)(nil)
