// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (PaymentPayment, error)
	GetPayment(ctx context.Context, id int64) (PaymentPayment, error)
	ListPayments(ctx context.Context) ([]PaymentPayment, error)
	ListUnpublishedSettledEvents(ctx context.Context, limit int32) ([]ListUnpublishedSettledEventsRow, error)
	MarkSettledEventPublished(ctx context.Context, id int64) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (PaymentPayment, error)
}

var _ Querier = (*Queries)(nil)
