// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
)

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, amount_cents, method, status, created_at
FROM payment.payments
ORDER BY id
`

func (q *Queries) ListPayments(ctx context.Context) ([]PaymentPayment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentPayment{}
	for rows.Next() {
		var i PaymentPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
