// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShippingShipment struct {
	ID             int64              `json:"id"`
	OrderID        int64              `json:"orderId"`
	Carrier        string             `json:"carrier"`
	TrackingNo     string             `json:"trackingNo"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	ShipRecipient  string             `json:"shipRecipient"`
	ShipPostalCode string             `json:"shipPostalCode"`
	ShipPrefecture string             `json:"shipPrefecture"`
	ShipCity       string             `json:"shipCity"`
	ShipLine1      string             `json:"shipLine1"`
}
