// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping.sql

package db

import (
	"context"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipping.shipments (order_id, carrier, tracking_no, status)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, carrier, tracking_no, status, created_at
`

type CreateShipmentParams struct {
	OrderID    int64  `json:"orderId"`
	Carrier    string `json:"carrier"`
	TrackingNo string `json:"trackingNo"`
	Status     string `json:"status"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.OrderID,
		arg.Carrier,
		arg.TrackingNo,
		arg.Status,
	)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, order_id, carrier, tracking_no, status, created_at
FROM shipping.shipments
WHERE id = $1
`

func (q *Queries) GetShipment(ctx context.Context, id int64) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listShipments = `-- name: ListShipments :many
SELECT id, order_id, carrier, tracking_no, status, created_at
FROM shipping.shipments
ORDER BY id
`

func (q *Queries) ListShipments(ctx context.Context) ([]ShippingShipment, error) {
	rows, err := q.db.Query(ctx, listShipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingShipment{}
	for rows.Next() {
		var i ShippingShipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Carrier,
			&i.TrackingNo,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipment = `-- name: UpdateShipment :one
UPDATE shipping.shipments
SET status = $2
WHERE id = $1
RETURNING id, order_id, carrier, tracking_no, status, created_at
`

type UpdateShipmentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, updateShipment, arg.ID, arg.Status)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
