// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping.sql

package db

import (
	"context"
)

const listShipments = `-- name: ListShipments :many
SELECT id, order_id, carrier, tracking_no, status, created_at
FROM shipping.shipments
ORDER BY id
`

func (q *Queries) ListShipments(ctx context.Context) ([]ShippingShipment, error) {
	rows, err := q.db.Query(ctx, listShipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingShipment{}
	for rows.Next() {
		var i ShippingShipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Carrier,
			&i.TrackingNo,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
