// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping.sql

package db

import (
	"context"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipping.shipments (order_id, carrier, tracking_no, status)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, carrier, tracking_no, status, created_at, ship_recipient, ship_postal_code, ship_prefecture, ship_city, ship_line1
`

type CreateShipmentParams struct {
	OrderID    int64  `json:"orderId"`
	Carrier    string `json:"carrier"`
	TrackingNo string `json:"trackingNo"`
	Status     string `json:"status"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.OrderID,
		arg.Carrier,
		arg.TrackingNo,
		arg.Status,
	)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
		&i.ShipRecipient,
		&i.ShipPostalCode,
		&i.ShipPrefecture,
		&i.ShipCity,
		&i.ShipLine1,
	)
	return i, err
}

const createShipmentForOrder = `-- name: CreateShipmentForOrder :one
INSERT INTO shipping.shipments (order_id, ship_recipient, ship_postal_code, ship_prefecture, ship_city, ship_line1)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, order_id, carrier, tracking_no, status, created_at, ship_recipient, ship_postal_code, ship_prefecture, ship_city, ship_line1
`

type CreateShipmentForOrderParams struct {
	OrderID        int64  `json:"orderId"`
	ShipRecipient  string `json:"shipRecipient"`
	ShipPostalCode string `json:"shipPostalCode"`
	ShipPrefecture string `json:"shipPrefecture"`
	ShipCity       string `json:"shipCity"`
	ShipLine1      string `json:"shipLine1"`
}

// ADR-[[202606211200]] / ADR-[[202606261704]]
func (q *Queries) CreateShipmentForOrder(ctx context.Context, arg CreateShipmentForOrderParams) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, createShipmentForOrder,
		arg.OrderID,
		arg.ShipRecipient,
		arg.ShipPostalCode,
		arg.ShipPrefecture,
		arg.ShipCity,
		arg.ShipLine1,
	)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
		&i.ShipRecipient,
		&i.ShipPostalCode,
		&i.ShipPrefecture,
		&i.ShipCity,
		&i.ShipLine1,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, order_id, carrier, tracking_no, status, created_at, ship_recipient, ship_postal_code, ship_prefecture, ship_city, ship_line1
FROM shipping.shipments
WHERE id = $1
`

func (q *Queries) GetShipment(ctx context.Context, id int64) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
		&i.ShipRecipient,
		&i.ShipPostalCode,
		&i.ShipPrefecture,
		&i.ShipCity,
		&i.ShipLine1,
	)
	return i, err
}

const listShipments = `-- name: ListShipments :many
SELECT id, order_id, carrier, tracking_no, status, created_at, ship_recipient, ship_postal_code, ship_prefecture, ship_city, ship_line1
FROM shipping.shipments
ORDER BY id
`

func (q *Queries) ListShipments(ctx context.Context) ([]ShippingShipment, error) {
	rows, err := q.db.Query(ctx, listShipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingShipment{}
	for rows.Next() {
		var i ShippingShipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Carrier,
			&i.TrackingNo,
			&i.Status,
			&i.CreatedAt,
			&i.ShipRecipient,
			&i.ShipPostalCode,
			&i.ShipPrefecture,
			&i.ShipCity,
			&i.ShipLine1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipment = `-- name: UpdateShipment :one
UPDATE shipping.shipments
SET status = $2
WHERE id = $1
RETURNING id, order_id, carrier, tracking_no, status, created_at, ship_recipient, ship_postal_code, ship_prefecture, ship_city, ship_line1
`

type UpdateShipmentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (ShippingShipment, error) {
	row := q.db.QueryRow(ctx, updateShipment, arg.ID, arg.Status)
	var i ShippingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNo,
		&i.Status,
		&i.CreatedAt,
		&i.ShipRecipient,
		&i.ShipPostalCode,
		&i.ShipPrefecture,
		&i.ShipCity,
		&i.ShipLine1,
	)
	return i, err
}
