/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Order Service API
 * 注文ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import type { Order } from "../model";

import { orderFetch } from "../../mutator";

export type listOrdersResponse200 = {
  data: Order[];
  status: 200;
};

export type listOrdersResponseSuccess = listOrdersResponse200 & {
  headers: Headers;
};

export type listOrdersResponse = listOrdersResponseSuccess;

export const getListOrdersUrl = () => {
  return `/orders`;
};

/**
 * @summary 注文一覧
 */
export const listOrders = async (options?: RequestInit): Promise<listOrdersResponse> => {
  return orderFetch<listOrdersResponse>(getListOrdersUrl(), {
    ...options,
    method: "GET",
  });
};
