/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shipping Service API
 * 配送ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary 配送一覧
 */
export const ListShipmentsResponseItem = zod.object({
  id: zod.number(),
  orderId: zod.number(),
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});
export const ListShipmentsResponse = zod.array(ListShipmentsResponseItem);
