/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shipping Service API
 * 配送ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateShipmentRequest,
  ErrorResponse,
  Shipment,
  UpdateShipmentRequest,
} from "../model";

import { shippingFetch } from "../../mutator";

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type listShipmentsResponse200 = {
  data: Shipment[];
  status: 200;
};

export type listShipmentsResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type listShipmentsResponseSuccess = listShipmentsResponse200 & {
  headers: Headers;
};
export type listShipmentsResponseError = listShipmentsResponseDefault & {
  headers: Headers;
};

export type listShipmentsResponse = listShipmentsResponseSuccess | listShipmentsResponseError;

export const getListShipmentsUrl = () => {
  return `/shipments`;
};

/**
 * @summary 配送一覧
 */
export const listShipments = async (options?: RequestInit): Promise<listShipmentsResponse> => {
  return shippingFetch<listShipmentsResponse>(getListShipmentsUrl(), {
    ...options,
    method: "GET",
  });
};

export type createShipmentResponse201 = {
  data: Shipment;
  status: 201;
};

export type createShipmentResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 201>;
};

export type createShipmentResponseSuccess = createShipmentResponse201 & {
  headers: Headers;
};
export type createShipmentResponseError = createShipmentResponseDefault & {
  headers: Headers;
};

export type createShipmentResponse = createShipmentResponseSuccess | createShipmentResponseError;

export const getCreateShipmentUrl = () => {
  return `/shipments`;
};

/**
 * @summary 配送を作成
 */
export const createShipment = async (
  createShipmentRequest: CreateShipmentRequest,
  options?: RequestInit,
): Promise<createShipmentResponse> => {
  return shippingFetch<createShipmentResponse>(getCreateShipmentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createShipmentRequest),
  });
};

export type getShipmentResponse200 = {
  data: Shipment;
  status: 200;
};

export type getShipmentResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type getShipmentResponseSuccess = getShipmentResponse200 & {
  headers: Headers;
};
export type getShipmentResponseError = getShipmentResponseDefault & {
  headers: Headers;
};

export type getShipmentResponse = getShipmentResponseSuccess | getShipmentResponseError;

export const getGetShipmentUrl = (id: number) => {
  return `/shipments/${id}`;
};

/**
 * @summary 配送を取得
 */
export const getShipment = async (
  id: number,
  options?: RequestInit,
): Promise<getShipmentResponse> => {
  return shippingFetch<getShipmentResponse>(getGetShipmentUrl(id), {
    ...options,
    method: "GET",
  });
};

export type updateShipmentResponse200 = {
  data: Shipment;
  status: 200;
};

export type updateShipmentResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type updateShipmentResponseSuccess = updateShipmentResponse200 & {
  headers: Headers;
};
export type updateShipmentResponseError = updateShipmentResponseDefault & {
  headers: Headers;
};

export type updateShipmentResponse = updateShipmentResponseSuccess | updateShipmentResponseError;

export const getUpdateShipmentUrl = (id: number) => {
  return `/shipments/${id}`;
};

/**
 * @summary 配送を更新
 */
export const updateShipment = async (
  id: number,
  updateShipmentRequest: UpdateShipmentRequest,
  options?: RequestInit,
): Promise<updateShipmentResponse> => {
  return shippingFetch<updateShipmentResponse>(getUpdateShipmentUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateShipmentRequest),
  });
};
