/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shipping Service API
 * 配送ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary 配送一覧
 */
export const ListShipmentsResponseItem = zod.object({
  id: zod.number(),
  orderId: zod.number(),
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});
export const ListShipmentsResponse = zod.array(ListShipmentsResponseItem);

/**
 * @summary 配送を作成
 */
export const CreateShipmentBody = zod.object({
  orderId: zod.number(),
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
});

export const CreateShipmentResponse = zod.object({
  id: zod.number(),
  orderId: zod.number(),
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary 配送を取得
 */
export const GetShipmentParams = zod.object({
  id: zod.number().describe("リソース ID"),
});

export const GetShipmentResponse = zod.object({
  id: zod.number(),
  orderId: zod.number(),
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary 配送を更新
 */
export const UpdateShipmentParams = zod.object({
  id: zod.number().describe("リソース ID"),
});

export const UpdateShipmentBody = zod.object({
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
});

export const UpdateShipmentResponse = zod.object({
  id: zod.number(),
  orderId: zod.number(),
  carrier: zod.string(),
  trackingNo: zod.string(),
  status: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
});
