// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/rin2yh/study-architecture/server/internal/redisx"
	"github.com/rin2yh/study-architecture/server/shipping/internal/consumer"
	"github.com/rin2yh/study-architecture/server/shipping/internal/handler"
	"github.com/rin2yh/study-architecture/server/shipping/internal/rdb"
	"github.com/rin2yh/study-architecture/server/shipping/internal/worker"
)

func InitHandler(ctx context.Context) (*handler.Handler, error) {
	var err error
	pool, err := kessoku.Async(kessoku.Provide(rdb.NewPool)).Fn()(ctx)
	if err != nil {
		var zero *handler.Handler
		return zero, err
	}
	shipmentQuery := kessoku.Bind[handler.Query](kessoku.Provide(rdb.NewShipmentQuery)).Fn()(pool)
	shipmentCommand := kessoku.Bind[handler.Command](kessoku.Provide(rdb.NewShipmentCommand)).Fn()(pool)
	handler0 := kessoku.Provide(handler.New).Fn()(shipmentQuery, shipmentCommand)
	return handler0, nil
}
func InitWorker(ctx0 context.Context) (*worker.Worker, error) {
	var err0 error
	client, err0 := kessoku.Provide(redisx.NewClient).Fn()()
	if err0 != nil {
		var zero *worker.Worker
		return zero, err0
	}
	var err1 error
	pool0, err1 := kessoku.Async(kessoku.Provide(rdb.NewPool)).Fn()(ctx0)
	if err1 != nil {
		var zero *worker.Worker
		return zero, err1
	}
	shipmentCommand0 := kessoku.Provide(rdb.NewShipmentCommand).Fn()(pool0)
	shipmentCreator := kessoku.Provide(func(c *rdb.ShipmentCommand) consumer.ShipmentCreator {
		return c
	}).Fn()(shipmentCommand0)
	shipmentCanceller := kessoku.Provide(func(c *rdb.ShipmentCommand) consumer.ShipmentCanceller {
		return c
	}).Fn()(shipmentCommand0)
	consumer0 := kessoku.Provide(consumer.New).Fn()(client, shipmentCreator)
	cancelConsumer := kessoku.Provide(consumer.NewCancel).Fn()(client, shipmentCanceller)
	worker0 := kessoku.Provide(worker.New).Fn()(consumer0, cancelConsumer)
	return worker0, nil
}
