/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Product Service API
 * 商品ドメイン。Step 0 の薄い骨格（liveness + 一覧）。
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProductRequest, ErrorResponse, Product, UpdateProductRequest } from "../model";

import { productFetch } from "../../mutator";

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type listProductsResponse200 = {
  data: Product[];
  status: 200;
};

export type listProductsResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type listProductsResponseSuccess = listProductsResponse200 & {
  headers: Headers;
};
export type listProductsResponseError = listProductsResponseDefault & {
  headers: Headers;
};

export type listProductsResponse = listProductsResponseSuccess | listProductsResponseError;

export const getListProductsUrl = () => {
  return `/products`;
};

/**
 * @summary 商品一覧
 */
export const listProducts = async (options?: RequestInit): Promise<listProductsResponse> => {
  return productFetch<listProductsResponse>(getListProductsUrl(), {
    ...options,
    method: "GET",
  });
};

export type createProductResponse201 = {
  data: Product;
  status: 201;
};

export type createProductResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 201>;
};

export type createProductResponseSuccess = createProductResponse201 & {
  headers: Headers;
};
export type createProductResponseError = createProductResponseDefault & {
  headers: Headers;
};

export type createProductResponse = createProductResponseSuccess | createProductResponseError;

export const getCreateProductUrl = () => {
  return `/products`;
};

/**
 * @summary 商品を作成
 */
export const createProduct = async (
  createProductRequest: CreateProductRequest,
  options?: RequestInit,
): Promise<createProductResponse> => {
  return productFetch<createProductResponse>(getCreateProductUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductRequest),
  });
};

export type getProductResponse200 = {
  data: Product;
  status: 200;
};

export type getProductResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type getProductResponseSuccess = getProductResponse200 & {
  headers: Headers;
};
export type getProductResponseError = getProductResponseDefault & {
  headers: Headers;
};

export type getProductResponse = getProductResponseSuccess | getProductResponseError;

export const getGetProductUrl = (id: number) => {
  return `/products/${id}`;
};

/**
 * @summary 商品を取得
 */
export const getProduct = async (
  id: number,
  options?: RequestInit,
): Promise<getProductResponse> => {
  return productFetch<getProductResponse>(getGetProductUrl(id), {
    ...options,
    method: "GET",
  });
};

export type updateProductResponse200 = {
  data: Product;
  status: 200;
};

export type updateProductResponseDefault = {
  data: ErrorResponse;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type updateProductResponseSuccess = updateProductResponse200 & {
  headers: Headers;
};
export type updateProductResponseError = updateProductResponseDefault & {
  headers: Headers;
};

export type updateProductResponse = updateProductResponseSuccess | updateProductResponseError;

export const getUpdateProductUrl = (id: number) => {
  return `/products/${id}`;
};

/**
 * @summary 商品を更新
 */
export const updateProduct = async (
  id: number,
  updateProductRequest: UpdateProductRequest,
  options?: RequestInit,
): Promise<updateProductResponse> => {
  return productFetch<updateProductResponse>(getUpdateProductUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProductRequest),
  });
};
